version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:13.9.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ arch }}-{{ checksum "yarn.lock" }}
            - v2-npm-deps-{{ arch }} # used if above checksum fails
      - run: yarn
      - save_cache:
          key: v2-npm-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test
workflows:
  version: 2
  runner:
    jobs:
      - build
